In [6]:
import pandas as pd

## Reading Data

In [7]:
df= pd.read_csv('datasets/titanic.csv')

## Exploring and Inspecting Data

In [6]:
df.head()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
0,791,792,0,1,0.2000,NaN,0,1,0,0.0,1,0,0,0,0,0,1
1,792,793,0,0,0.3500,NaN,0,0,1,1.0,0,0,0,1,0,0,1
2,793,794,0,1,0.3500,NaN,1,0,0,0.0,1,0,0,0,1,0,0
3,794,795,0,1,0.3125,NaN,0,0,1,0.0,1,0,0,0,0,0,1
4,795,796,0,1,0.4875,NaN,0,1,0,0.0,1,0,0,0,0,0,1

In [ ]:
df.tail()

In [8]:
df.describe()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
count,100.000000,100.000000,100.000000,100.000000,81.000000,76.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.00,100.00000,100.000000,100.00000,100.000000,100.000000
mean,840.500000,841.500000,0.360000,0.650000,0.354205,0.049435,0.230000,0.200000,0.57000,0.104000,0.770000,0.01,0.08000,0.140000,0.21000,0.040000,0.740000
std,29.011492,29.011492,0.482418,0.479372,0.169369,0.054461,0.422953,0.402015,0.49757,0.207885,0.422953,0.10,0.27266,0.348735,0.40936,0.196946,0.440844
min,791.000000,792.000000,0.000000,0.000000,0.005250,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00,0.00000,0.000000,0.00000,0.000000,0.000000
25%,815.750000,816.750000,0.000000,0.000000,0.262500,0.015412,0.000000,0.000000,0.00000,0.000000,1.000000,0.00,0.00000,0.000000,0.00000,0.000000,0.000000
50%,840.500000,841.500000,0.000000,1.000000,0.350000,0.025374,0.000000,0.000000,1.00000,0.000000,1.000000,0.00,0.00000,0.000000,0.00000,0.000000,1.000000
75%,865.250000,866.250000,1.000000,1.000000,0.437500,0.059044,0.000000,0.000000,1.00000,0.100000,1.000000,0.00,0.00000,0.000000,0.00000,0.000000,1.000000
max,890.000000,891.000000,1.000000,1.000000,0.925000,0.321798,1.000000,1.000000,1.00000,1.000000,1.000000,1.00,1.00000,1.000000,1.00000,1.000000,1.000000

In [19]:
df.isnull().sum()

Unnamed: 0      0
PassengerId     0
Survived        0
Sex             0
Age            19
Fare           24
Pclass_1        0
Pclass_2        0
Pclass_3        0
Family_size     0
Title_1         0
Title_2         0
Title_3         0
Title_4         0
Emb_1           0
Emb_2           0
Emb_3           0
dtype: int64

## Handling missing or null values

**drop rows with null values**

In [14]:
df.dropna(inplace=True)

**Fill null values with a specific value**

In [20]:
df.fillna(value=10)

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
0,791,792,0,1,0.2000,10.000000,0,1,0,0.0,1,0,0,0,0,0,1
1,792,793,0,0,0.3500,10.000000,0,0,1,1.0,0,0,0,1,0,0,1
2,793,794,0,1,0.3500,10.000000,1,0,0,0.0,1,0,0,0,1,0,0
3,794,795,0,1,0.3125,10.000000,0,0,1,0.0,1,0,0,0,0,0,1
4,795,796,0,1,0.4875,10.000000,0,1,0,0.0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,886,887,0,1,10.0000,0.025374,0,1,0,0.0,1,0,0,0,0,0,1
96,887,888,1,0,10.0000,0.058556,1,0,0,0.0,0,0,0,1,0,0,1
97,888,889,0,0,10.0000,0.045771,0,0,1,0.3,0,0,0,1,0,0,1
98,889,890,1,1,10.0000,0.058556,1,0,0,0.0,1,0,0,0,1,0,0
99,890,891,0,1,10.0000,0.015127,0,0,1,0.0,1,0,0,0,0,1,0

**Fill null value with mean, median, mode**

In [37]:
df['Fare'] = df['Fare'].fillna(value=df['Fare'].mean())

In [ ]:
df['Fare'] = df['Fare'].fillna(value=df['Fare'].median())

In [ ]:
df['Fare'] = df['Fare'].fillna(value=df['Fare'].mode())

**Forward Fill**

In [ ]:
df_filled = df.fillna(method='ffill')

**Backward FIll**

In [ ]:
df_filled = df.fillna(method='bfill')

**Selecting Specific columns**

In [38]:
df.head()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
0,791,792,0,1,0.2000,0.049435,0,1,0,0.0,1,0,0,0,0,0,1
1,792,793,0,0,0.3500,0.049435,0,0,1,1.0,0,0,0,1,0,0,1
2,793,794,0,1,0.3500,0.049435,1,0,0,0.0,1,0,0,0,1,0,0
3,794,795,0,1,0.3125,0.049435,0,0,1,0.0,1,0,0,0,0,0,1
4,795,796,0,1,0.4875,0.049435,0,1,0,0.0,1,0,0,0,0,0,1

In [13]:
df[['PassengerId','Age']]

    PassengerId     Age
0           792  0.2000
1           793  0.3500
2           794  0.3500
3           795  0.3125
4           796  0.4875
..          ...     ...
95          887     NaN
96          888     NaN
97          889     NaN
98          890     NaN
99          891     NaN

[100 rows x 2 columns]

## loc[ ] vs. iloc[ ] in Pandas:

Both loc[ ] and iloc[ ] are used to select data from a Pandas DataFrame or Series, but they differ in how they access the data.

1. loc[ ]: Label-based Indexing
loc[ ] is used to select data by the label of rows and columns. It allows you to access groups of rows and columns by their names (or labels).
It works with index labels (both row and column labels) and can also accept boolean arrays for filtering.

In [1]:
student_dict = {
    'name':['Abdullah','John','Jacob','Emma','Sarah','Shamraiz'],
    'iq':[100,90,120,80,0,0],
    'marks':[80,70,100,50,0,0],
    'package':[10,7,14,2,0,0]
}

In [68]:
data = pd.DataFrame(student_dict)

In [69]:
data.head()

       name   iq  marks  package
0  Abdullah  100     80       10
1      John   90     70        7
2     Jacob  120    100       14
3      Emma   80     50        2
4     Sarah    0      0        0

In [74]:
data.loc[0:3,['name','marks']]

       name  marks
0  Abdullah     80
1      John     70
2     Jacob    100
3      Emma     50

changing index from 0 1 2 3 to names to clear how loc used labels not position

In [65]:
data.set_index('name',inplace=True)
data

           iq  marks  package
name
Abdullah  100     80       10
John       90     70        7
Jacob     120    100       14
Emma       80     50        2
Sarah       0      0        0
Shamraiz    0      0        0

In [ ]:
data.loc[['Abdullah':'John'],['name','marks']]

2. iloc[ ]: Integer-based Indexing
iloc[ ] is used to select data by integer position. It allows you to access rows and columns using their numerical positions, like an array index in Python.
It works purely with integer positions, similar to how Python lists or NumPy arrays work.

In [75]:
data.iloc[0:3,[0,2]]

       name  marks
0  Abdullah     80
1      John     70
2     Jacob    100

In [67]:
data.iloc[0]

iq         100
marks       80
package     10
Name: Abdullah, dtype: int64

In [82]:
df.tail()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
95,886,887,0,1,0.049435,0.025374,0,1,0,0.0,1,0,0,0,0,0,1
96,887,888,1,0,0.049435,0.058556,1,0,0,0.0,0,0,0,1,0,0,1
97,888,889,0,0,0.049435,0.045771,0,0,1,0.3,0,0,0,1,0,0,1
98,889,890,1,1,0.049435,0.058556,1,0,0,0.0,1,0,0,0,1,0,0
99,890,891,0,1,0.049435,0.015127,0,0,1,0.0,1,0,0,0,0,1,0

## Filtering and use of AND OR operators

In [85]:
df[(df['PassengerId'] > 800) & (df['PassengerId'] < 850)]

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
9,800,801,0,1,0.425000,0.049435,0,1,0,0.0,1,0,0,0,0,0,1
10,801,802,1,0,0.387500,0.049435,0,1,0,0.2,1,0,0,0,0,0,1
11,802,803,1,1,0.137500,0.049435,1,0,0,0.3,0,0,1,0,0,0,1
12,803,804,1,1,0.005250,0.049435,0,0,1,0.1,0,0,1,0,1,0,0
13,804,805,1,1,0.337500,0.049435,0,0,1,0.0,1,0,0,0,0,0,1
14,805,806,0,1,0.387500,0.049435,0,0,1,0.0,1,0,0,0,0,0,1
15,806,807,0,1,0.487500,0.049435,1,0,0,0.0,1,0,0,0,0,0,1
16,807,808,0,0,0.225000,0.049435,0,0,1,0.0,0,0,0,1,0,0,1
17,808,809,0,1,0.487500,0.049435,0,1,0,0.0,1,0,0,0,0,0,1
18,809,810,1,0,0.412500,0.049435,1,0,0,0.1,1,0,0,0,0,0,1
19,810,811,0,1,0.325000,0.049435,0,0,1,0.0,1,0,0,0,0,0,1
20,811,812,0,1,0.487500,0.049435,0,0,1,0.0,1,0,0,0,0,0,1
21,812,813,0,1,0.437500,0.049435,0,1,0,0.0,1,0,0,0,0,0,1
22,813,814,0,0,0.075000,0.049435,0,0,1,0.6,0,0,0,1,0,0,1
23,814,815,0,1,0.381250,0.049435,0,0,1,0.0,1,0,0,0,0,0,1
24,815,816,0,1,0.350000,0.000000,1,0,0,0.0,1,0,0,0,0,0,1
25,816,817,0,0,0.287500,0.015469,0,0,1,0.0,0,0,0,1,0,0,1
26,817,818,0,1,0.387500,0.072227,0,1,0,0.2,1,0,0,0,1,0,0
27,818,819,0,1,0.537500,0.012590,0,0,1,0.0,1,0,0,0,0,0,1
28,819,820,0,1,0.125000,0.054457,0,0,1,0.5,0,0,1,0,0,0,1
29,820,821,1,0,0.650000,0.182500,1,0,0,0.2,1,0,0,0,0,0,1
30,821,822,1,1,0.337500,0.016908,0,0,1,0.0,1,0,0,0,0,0,1
31,822,823,0,1,0.475000,0.000000,1,0,0,0.0,1,0,0,0,0,0,1
32,823,824,1,0,0.337500,0.024350,0,0,1,0.1,1,0,0,0,0,0,1
33,824,825,0,1,0.025000,0.077465,0,0,1,0.5,0,0,1,0,0,0,1
34,825,826,0,1,0.350000,0.013565,0,0,1,0.0,1,0,0,0,0,1,0
35,826,827,0,1,0.350000,0.110272,0,0,1,0.0,1,0,0,0,0,0,1
36,827,828,1,1,0.012500,0.072227,0,1,0,0.2,0,0,1,0,1,0,0
37,828,829,1,1,0.350000,0.015127,0,0,1,0.0,1,0,0,0,0,1,0
38,829,830,1,0,0.775000,0.156150,1,0,0,0.0,1,0,0,0,0,0,0
39,830,831,1,0,0.187500,0.028213,0,0,1,0.1,1,0,0,0,1,0,0
40,831,832,1,1,0.010375,0.036598,0,1,0,0.2,0,0,1,0,0,0,1
41,832,833,0,1,0.350000,0.014110,0,0,1,0.0,1,0,0,0,1,0,0
42,833,834,0,1,0.287500,0.015330,0,0,1,0.0,1,0,0,0,0,0,1
43,834,835,0,1,0.225000,0.016201,0,0,1,0.0,1,0,0,0,0,0,1
44,835,836,1,0,0.487500,0.162314,1,0,0,0.2,0,0,0,1,1,0,0
45,836,837,0,1,0.262500,0.016908,0,0,1,0.0,1,0,0,0,0,0,1
46,837,838,0,1,0.350000,0.015713,0,0,1,0.0,1,0,0,0,0,0,1
47,838,839,1,1,0.400000,0.110272,0,0,1,0.0,1,0,0,0,0,0,1
48,839,840,1,1,0.350000,0.057971,1,0,0,0.0,1,0,0,0,1,0,0
49,840,841,0,1,0.250000,0.015469,0,0,1,0.0,1,0,0,0,0,0,1
50,841,842,0,1,0.200000,0.020495,0,1,0,0.0,1,0,0,0,0,0,1
51,842,843,1,0,0.375000,0.060508,1,0,0,0.0,0,0,0,1,1,0,0
52,843,844,0,1,0.431250,0.012565,0,0,1,0.0,1,0,0,0,1,0,0
53,844,845,0,1,0.212500,0.016908,0,0,1,0.0,1,0,0,0,0,0,1
54,845,846,0,1,0.525000,0.014737,0,0,1,0.0,1,0,0,0,0,0,1
55,846,847,0,1,0.350000,0.135753,0,0,1,1.0,1,0,0,0,0,0,1
56,847,848,0,1,0.437500,0.015412,0,0,1,0.0,1,0,0,0,1,0,0
57,848,849,0,1,0.350000,0.064412,0,1,0,0.1,1,0,0,0,0,0,1

In [87]:
df.head()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
0,791,792,0,1,0.2000,0.049435,0,1,0,0.0,1,0,0,0,0,0,1
1,792,793,0,0,0.3500,0.049435,0,0,1,1.0,0,0,0,1,0,0,1
2,793,794,0,1,0.3500,0.049435,1,0,0,0.0,1,0,0,0,1,0,0
3,794,795,0,1,0.3125,0.049435,0,0,1,0.0,1,0,0,0,0,0,1
4,795,796,0,1,0.4875,0.049435,0,1,0,0.0,1,0,0,0,0,0,1

In [88]:
df['Survived'].unique()

array([0, 1])

In [89]:
df[(df['PassengerId'] > 800)| (df['Survived'] == 1)]

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
5,796,797,1,0,0.612500,0.049435,1,0,0,0.0,0,1,0,0,0,0,1
6,797,798,1,0,0.387500,0.049435,0,0,1,0.0,1,0,0,0,0,0,1
9,800,801,0,1,0.425000,0.049435,0,1,0,0.0,1,0,0,0,0,0,1
10,801,802,1,0,0.387500,0.049435,0,1,0,0.2,1,0,0,0,0,0,1
11,802,803,1,1,0.137500,0.049435,1,0,0,0.3,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,886,887,0,1,0.049435,0.025374,0,1,0,0.0,1,0,0,0,0,0,1
96,887,888,1,0,0.049435,0.058556,1,0,0,0.0,0,0,0,1,0,0,1
97,888,889,0,0,0.049435,0.045771,0,0,1,0.3,0,0,0,1,0,0,1
98,889,890,1,1,0.049435,0.058556,1,0,0,0.0,1,0,0,0,1,0,0
99,890,891,0,1,0.049435,0.015127,0,0,1,0.0,1,0,0,0,0,1,0

## Group By

<img align="center" width="700" height="500"  src="images/groupbyfinal.png"  >

Grouping and Aggregating

In [90]:
df.groupby('Survived')['Age'].mean()

Survived
0    0.287581
1    0.311798
Name: Age, dtype: float64

In [ ]:
df.groupby('Survived').get_group(1)

# Exam Solutions

In [5]:
import pandas as pd

# Creating a dictionary with the data
data_dict = {
    "name": [
        "Sean", "Brandon", "Jessica", "Alice", "Brandon", "Alice", 
        "Sean", "Jessica", "Brandon", "Sean", "Alice", "Jessica", 
        "Sean", "Brandon", "Alice", "Jessica", "Brandon", "Alice", 
        "Sean", "Brandon"
    ],
    "item": [
        "Orange Chicken", "Chow Mein", "Honey Walnut Shrimp", "Fried Rice", 
        "Eggplant Tofu", "Kung Pao Chicken", "Broccoli Beef", 
        "Vegetable Spring Rolls", "Sweet & Sour Pork", "Chow Mein", 
        "Fried Rice", "Orange Chicken", "Broccoli Beef", "Kung Pao Chicken", 
        "Honey Walnut Shrimp", "Eggplant Tofu", "Chow Mein", 
        "Sweet & Sour Pork", "Vegetable Spring Rolls", "Fried Rice"
    ],
    "size": [
        "large", "medium", "medium", "large", "small", "large", 
        "small", "small", "small", "medium", "large", "large", 
        "small", "large", "medium", "small", "medium", "small", 
        "small", "medium"
    ],
    "veg": [
        0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 
        1, 0, 0, 0, 0, 1, 1, 0, 1, 1
    ],
    "premium": [
        0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 
        0, 0, 0, 1, 1, 0, 0, 1, 0, 0
    ],
    "price": [
        11.4, 8.7, 11.7, 9.2, 5.4, 12.0, 
        5.4, 4.0, 10.5, 8.7, 9.2, 11.4, 
        5.4, 12.0, 11.7, 5.4, 8.7, 10.5, 
        4.0, 9.2
    ]
}

# Converting the dictionary into a DataFrame
df = pd.DataFrame(data_dict)

df.head()

      name                 item    size  veg  premium  price
0     Sean       Orange Chicken   large    0        0   11.4
1  Brandon            Chow Mein  medium    1        0    8.7
2  Jessica  Honey Walnut Shrimp  medium    0        1   11.7
3    Alice           Fried Rice   large    1        0    9.2
4  Brandon        Eggplant Tofu   small    1        0    5.4

Problem 1

In [11]:
df.loc[(df['veg'] == 1) & (df['price'] > 7.5)]

       name        item    size  veg  premium  price
1   Brandon   Chow Mein  medium    1        0    8.7
3     Alice  Fried Rice   large    1        0    9.2
9      Sean   Chow Mein  medium    1        0    8.7
10    Alice  Fried Rice   large    1        0    9.2
16  Brandon   Chow Mein  medium    1        0    8.7
19  Brandon  Fried Rice  medium    1        0    9.2

problem 2

In [18]:
df.groupby('item').filter(lambda a:len(a)>=3)

       name        item    size  veg  premium  price
1   Brandon   Chow Mein  medium    1        0    8.7
3     Alice  Fried Rice   large    1        0    9.2
9      Sean   Chow Mein  medium    1        0    8.7
10    Alice  Fried Rice   large    1        0    9.2
16  Brandon   Chow Mein  medium    1        0    8.7
19  Brandon  Fried Rice  medium    1        0    9.2

problem 3

In [38]:
# df['main'] = df['item'].str.split(' ').str[-1]

In [39]:
df['main'] = df["item"].str.extract(r"(\w+)$")

In [40]:
df.head()

      name                 item    size  veg  premium  price     main
0     Sean       Orange Chicken   large    0        0   11.4  Chicken
1  Brandon            Chow Mein  medium    1        0    8.7     Mein
2  Jessica  Honey Walnut Shrimp  medium    0        1   11.7   Shrimp
3    Alice           Fried Rice   large    1        0    9.2     Rice
4  Brandon        Eggplant Tofu   small    1        0    5.4     Tofu

problem 4

In [55]:
exclude_mains = ['Chicken','Mein']

In [60]:
# ~ is reversing the True False values because we only want those records which dont contains items in exclude_mains list mentioned above
entrees = ~df["main"].isin(exclude_mains)
entrees

0     False
1     False
2      True
3      True
4      True
5     False
6      True
7      True
8      True
9     False
10     True
11    False
12     True
13    False
14     True
15     True
16    False
17     True
18     True
19     True
Name: main, dtype: bool

In [61]:
df[entrees]

       name                    item    size  veg  premium  price    main
2   Jessica     Honey Walnut Shrimp  medium    0        1   11.7  Shrimp
3     Alice              Fried Rice   large    1        0    9.2    Rice
4   Brandon           Eggplant Tofu   small    1        0    5.4    Tofu
6      Sean           Broccoli Beef   small    0        0    5.4    Beef
7   Jessica  Vegetable Spring Rolls   small    1        0    4.0   Rolls
8   Brandon       Sweet & Sour Pork   small    0        1   10.5    Pork
10    Alice              Fried Rice   large    1        0    9.2    Rice
12     Sean           Broccoli Beef   small    0        0    5.4    Beef
14    Alice     Honey Walnut Shrimp  medium    0        1   11.7  Shrimp
15  Jessica           Eggplant Tofu   small    1        0    5.4    Tofu
17    Alice       Sweet & Sour Pork   small    0        1   10.5    Pork
18     Sean  Vegetable Spring Rolls   small    1        0    4.0   Rolls
19  Brandon              Fried Rice  medium    1        0    9.2    Rice

Problem 5

In [63]:
main_revenue = df.groupby('main')['price'].sum()

In [64]:
main_revenue

main
Beef       10.8
Chicken    46.8
Mein       26.1
Pork       21.0
Rice       27.6
Rolls       8.0
Shrimp     23.4
Tofu       10.8
Name: price, dtype: float64

Problem 6

In [65]:
position = len(main_revenue)//2

In [73]:
main_revenue.sort_values().iloc[position]

np.float64(23.4)

breakdown of problem 6

In [71]:
# First find mid position for median\
position = len(main_revenue)//2
position

4

In [75]:
# sort main revenue in order to get median
sort_main_revenue = main_revenue.sort_values()
sort_main_revenue

main
Rolls       8.0
Beef       10.8
Tofu       10.8
Pork       21.0
Shrimp     23.4
Mein       26.1
Rice       27.6
Chicken    46.8
Name: price, dtype: float64

In [83]:
# simply select the value at mid position that found in above code
sort_main_revenue.iloc[position]

np.float64(23.4)

In [84]:
# 23.4 is the median

Problem 7

In [85]:
normal_data = {
    "size": ["small", "medium", "large"],
    "normal_price": [5.4, 8.7, 11.4]
}
normal = pd.DataFrame(normal_data)

premium_data = {
    "size": ["large", "medium", "small"],
    "premium_price": [11.0, 11.7, 6.9]
}
premium = pd.DataFrame(premium_data)

In [93]:
# The merge() function is used to join two DataFrames (normal and premium) based on a common column.
# In this case, we are merging the 'normal' DataFrame with the 'premium' DataFrame.
# right=premium: Specifies that the 'premium' DataFrame is the right DataFrame in the merge.
# left_on='size': Uses the 'size' column from the 'normal' DataFrame as the key for the join.
# right_on='size': Uses the 'size' column from the 'premium' DataFrame as the key for the join.

# The result is a new DataFrame (prices) that contains the 'size' column, 
# along with both 'normal_price' and 'premium_price' columns for matching sizes.

prices = normal.merge(right=premium,left_on='size',right_on='size')

In [94]:
prices.head()

     size  normal_price  premium_price
0   small           5.4            6.9
1  medium           8.7           11.7
2   large          11.4           11.0

In [95]:
prices['diff'] = abs(prices['normal_price'] - prices['premium_price'])

In [96]:
prices.head()

     size  normal_price  premium_price  diff
0   small           5.4            6.9   1.5
1  medium           8.7           11.7   3.0
2   large          11.4           11.0   0.4